// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: personal.sql

package db

import (
	"context"
)

const createPersonal = `-- name: CreatePersonal :one
INSERT INTO personal (
  account_id,
  amount
) VALUES (
  $1, $2
) RETURNING id, account_id, amount, created_at
`

type CreatePersonalParams struct {
	AccountID int64 `json:"account_id"`
	Amount    int64 `json:"amount"`
}

func (q *Queries) CreatePersonal(ctx context.Context, arg CreatePersonalParams) (Personal, error) {
	row := q.db.QueryRowContext(ctx, createPersonal, arg.AccountID, arg.Amount)
	var i Personal
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonal = `-- name: GetPersonal :one
SELECT id, account_id, amount, created_at FROM personal
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPersonal(ctx context.Context, id int64) (Personal, error) {
	row := q.db.QueryRowContext(ctx, getPersonal, id)
	var i Personal
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listpersonal = `-- name: Listpersonal :many
SELECT id, account_id, amount, created_at FROM personal
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListpersonalParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) Listpersonal(ctx context.Context, arg ListpersonalParams) ([]Personal, error) {
	rows, err := q.db.QueryContext(ctx, listpersonal, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Personal
	for rows.Next() {
		var i Personal
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
